### PR TITLE
Removes typo element.

### PR DESCRIPTION
**Pull request by abea**
Removes what seems like a typo in the allowed elements.

### CODE REVIEW

**Comment by boutell** [comment]
Is this about `nl`? It was valid in XHTML 2.0 so I'm not crazy, but I don't see it coming up in later versions / HTML5.

**Comment by abea** [comment]
I'm pretty sure it's not an HTML5 element. I wasn't familiar with that, so I guess I don't know if it should still be in here.

**Comment by abea** [comment]
Coming back to this, given it's an XHTML element it doesn't seem to make sense here.

**Comment by stuartromanek** [comment]
Good to get rid of this, yeah @abea @boutell ?

**Comment by abea** [comment]
I think so, yes.

**Pull request merged**
